version: '3.0'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - /docker/emps/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c0nygre
      MYSQL_DATABASE: fundmgt

    command: --explicit_defaults_for_timestamp

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    image: app:1.0.0
    links:
      - mysql:mysql
    ports:
      - "8081:8080"
    depends_on:
      - "mysql"
