FROM openjdk:11.0

ADD target/fundmgt-0.0.1-SNAPSHOT.jar app.jar

# RUN sh -c  'echo spring.datasource.url=jdbc:mysql://mysql:3306/fundmgt?serverTimezone=UTC >> application.properties'
# RUN sh -c 'echo spring.datasource.username=root >> application.properties'
# RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'

ENTRYPOINT ["java","-jar","/app.jar"]

